### ISSUE TITLE
De templates voor de nieuwsbrieven zitten nog niet in het systeem

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#101]

**Comment by Pieter1024** [comment]
Deze zijn inmiddels aangemaakt en worden automatisch geïmporteerd. Mieke, je kunt ze bekijken als je inlogt en een nieuwsbrief aan gaat maken onder 'Newsletters'.

**Comment by miekedewit** [comment]
Ziet er prima uit!
Dus ik sluit dit issue :)
