### ISSUE TITLE
Handmatig oude links overzetten

### ISSUE THREAD

**Issue by floort** [jonge-democraten/website#103]
De BaseImporterCommand heeft geen functionaliteit om links te migreren.
Met de volgende query zijn alle links uit de database te vinden:
SELECT * FROM joomla.2gWw_menu WHERE type = 'url';
Dat zijn er in mijn iets verouderde dump 7 in totaal.
Het is meer moeite om hier een workaround voor te schrijven dan het handmatig over te zetten.

**Comment by Pieter1024** [comment]
Kun je ze dan ook met de hand in jd_finalize.py zetten anders?

**Comment by Pieter1024** [comment]
De externe links staan nu in jd_finalize.py. Het gaat in totaal om ongeveer vijftien stuks.
