### ISSUE TITLE
Overzetten jdownloads documenten

### ISSUE THREAD

**Issue by floort** [jonge-democraten/website#104]
Hoi Mieke,

Joomla heeft een aantal bestanden in Jdownloads. Volgens mij moeten de meeste daarvan handmatig in de wolk gezet worden. Kan jij de verantwoordelijkheid op je nemen om die bestanden in de wolk te zetten?

Als je alles wat wel mee moet naar de nieuwe website kan aangeven kunnen die ook handmatig overgezet worden zodra de website klaar is.

**Comment by miekedewit** [comment]
Hoi Floor, 

Alles staat sowieso in de Wolk.
Het overzicht van welke documenten mee moeten nemen is nog niet compleet, ik hoop dit zo snel mogelijk te hebben.

**Comment by miekedewit** [comment]
Ik heb het voor mijzelf uitgezocht, dat zijn er vrij weinig. Ik heb nog niet van alle afdelingen een overzicht, ondanks meerdere malen vragen, dus daar zal ik nog even achteraan gaan.

**Comment by miekedewit** [comment]
Ik heb alle documenten die terug op de website moeten nu in de de ICT-team map in de wolk staan. 

Niet alle afdelingen hebben uiteindelijk hun documenten uitgezocht (soms hoeft niets mee), dus dat zullen ze zelf moeten doen na de migratie.

**Comment by Pieter1024** [comment]
@miekedewit dank je! Ik heb alle documenten geüpload naar de nieuwe omgeving. Daar staan ze in de Media Library zodat elke AS ze kan vinden en eventueel kan linken of verwijderen.
