### ISSUE TITLE
Data bij verkeerde afdelingen

### ISSUE THREAD

**Issue by malupasman** [jonge-democraten/website#105]
Op dit moment is er data van de ene afdeling bij de andere afdeling terechtgekomen (bijv. er staat informatie van Leiden-Haaglanden bij Amsterdam).

**Comment by Pieter1024** [comment]
Volgens mij is dit niet meer het geval. Ik heb het in elk geval gerepareerd bij de blog posts van afdelingen. @malupasman, kun je dat bevestigen?

**Comment by malupasman** [comment]
Klopt nu.
