### ISSUE TITLE
Permissions van de user

### ISSUE THREAD

**Issue by m-lies** [jonge-democraten/website#106]
Momenteel kan elke user zijn/haar toegangsrechten zelf veranderen (dus van user --> superuser), het is een tikkeltje onduidelijk wie er allemaal permissie heeft om dit te doen. Maar uiteraard niet de bedoeling dat normale gebruikers dit ook kunnen.

**Comment by floort** [comment]
Ik denk niet dat deze bij de data migratie hoort. Weet niet wie 'm het beste kan oppakken.

**Comment by Pieter1024** [comment]
De superuser-mogelijkheid is alleen beschikbaar voor leden van het ICT-team. Die kunnen echter op veel meer manieren hun bevoegdheden verhogen. Het is een beetje onhandig dat een gebruiker die zichzelf superuser maakt, dat ook blijft als hij uit het ICT-team is. Daarom lijkt het me waardevol om een opmerking daarover op te nemen in de wikipagina over aftredende teamleden. Dat heb ik inmiddels gedaan.

Ik sluit dit issue omdat ik denk dat het daarmee is afgedaan.
