### ISSUE TITLE
Offer view of upcoming events for department

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#11]
Should allow for setting next # of events or next time period.

**Comment by bashazeborg** [comment]
I close this issue. It looks good!

**Comment by Pieter1024** [comment]
I'm not sure what you meant by closing the issue, Bas. I think you may have misunderstood.

This issue was aimed at having the upcoming events as a column element, for example on the home page. We still need this, therefore I'm reopening the issue. We need such an overview in the sidebar as well, by the way.

**Comment by sh4wn** [comment]
Well, there's a templatetag so you could display the upcoming events (per department) anywhere in a template, but I'm not sure how to create a sidebar widget. Any docs on that?

**Comment by bashazeborg** [comment]
I did misunderstood! Sorry!

Met vrijzinnige groet,

Bas Hazeborg

--

Landelijk Bestuur der Jonge Democraten
Algemeen Secretaris

Telefoon: 06 38977320
E-mailadres: secretaris@jongedemocraten.nl

2015-03-30 14:59 GMT+02:00 Lucas <notifications@github.com>:

**Comment by Pieter1024** [comment]
Bas, no problem, of course.

Lucas, I'm working on a sidebar widget with tabs in branch feature/sidebartabs/#60. I'll finish that, but I could use your help.

Could you look at the file website/templates/elements/sidebar_tabs.html and explain which template tags I can use to produce the relevant information to fill that template?

**Comment by Pieter1024** [comment]
Excuse me, that should've been /website/templates/elements/tabs_sidebar_item.html.

**Comment by sh4wn** [comment]
I modified the tab a bit so it generates the proper URL, and also displays the site name.

**Comment by Pieter1024** [comment]
I think this works, so I close the issue.
