### ISSUE TITLE
We hebben een vierde type event-overzicht nodig

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#110]
In de ColumnElement-selectie bestaan maar drie opties voor Events-kolommen: current, all, all+main. Op meerdere afdelingssites komt het type 'alleen main' voor (voorbeeld: kolom 'Geplande activiteiten landelijk' op jdamsterdam.nl). Die hebben we nu niet.

**Comment by Pieter1024** [comment]
Euh, ik lijk me vergist te hebben. Er zijn twee opties: 'site' en 'site+main'. Alleen 'main' is ook nodig. Die zal ik toevoegen.

**Comment by Pieter1024** [comment]
Oh nee, weer verkeerd gekeken. Er zijn drie opties. Die zijn gedefinieerd in https://github.com/jonge-democraten/website/blob/master/website/jdpages/models.py#L275-L283. Ik ga een vierde optie, main, maken.

**Comment by bartromgens** [comment]
@Pieter1024: Ik was hier gisteravond al aan begonnen en had het vrijwel af. Bij het testen kwam ik alleen issue #112 tegen. 

Ik kan dit vanavond committen. Was niet veel werk. Alleen de demo_data goed krijgen, zodat de juiste column elementen worden gemaakt, was even uitzoeken.

**Comment by bartromgens** [comment]
Ik vind het overigens ook prima als jij dit doet, bijv. omdat je het nodig hebt of dit te laat leest... Eventueel kan ik later de demo_data fixen.

**Comment by Pieter1024** [comment]
Haha nee hoor, ik was gewoon enthousiast. Ik heb liever dat jij het doet. Ik zal mijn werk ermee vergelijken om na te gaan of ik op de goede weg was :+1:

**Comment by bartromgens** [comment]
Fixed in commit 56afaa69fa8e86483d6836e35770acecc26b246f and fullcalendar commit https://github.com/jonge-democraten/mezzanine-fullcalendar/commit/a2f1368f4f87350c3405e51b30c7100cda2b84cc.
