### ISSUE TITLE
We hebben een gebundelde-blog-categorieën-Column Element nodig

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#111]
Zoals gebruikt wordt in de linkerkolom van http://jongedemocraten.nl/amsterdam-de-druppel.html. Deze kolom is een bundeling van de categorieën van de kolommen rechts. Momenteel kunnen we dat nog niet.

**Comment by Pieter1024** [comment]
Als dit veel moeite is, kunnen we het ook overslaan. Mezzanine ondersteunt namelijk het toewijzen van meerdere categorieën aan een post. We kunnen alle posts uit de vijf categorieën van de Druppel dan ook een extra categorie 'Druppel' meegeven en dan in de linkerkolom de categorie 'Druppel' weergeven.

**Comment by Pieter1024** [comment]
Dat is dan aan @bartromgens om in te schatten.

**Comment by bartromgens** [comment]
De huidige structuur van column elementen ondersteunt dat niet. Ik kan een nieuw element type aanmaken dat meerdere blog categorieën kan bevatten. Dat element moet dan wel apart handmatig aangemaakt worden (we kunnen niet alle combinaties van tevoren aanmaken), en kan daarna geselecteerd worden in de kolom van een pagina. Dat introduceert dus extra complexiteit in de admin interface die maar voor een hele kleine groep toepasbaar is. 

Ik vind de optie om een extra blog categorie voor een kolom aan te maken mooier. Ook is mijn ervaring dat het veel oplevert om een zo simpel mogelijke gebruikersinterface te hebben, ook al gaat dit ten kosten van geavanceerde functionaliteit. Deze beslissing laat ik uiteindelijk graag aan @miekedewit over.

**Comment by Pieter1024** [comment]
Duidelijk verhaal, @bartromgens. Het klinkt alsof het veel werk is om dit in te bouwen en er maar weinig gevallen zijn waarin mensen dit willen gebruiken. Ook is er een eenvoudig alternatief dat begrijpelijk is voor gebruikers. Het lijkt me daarom beter om voor de eenvoudige oplossing te gaan en in het specifieke geval van Amsterdam de categorie 'Druppel' met de hand toe te voegen aan al hun posts.

**Comment by Pieter1024** [comment]
Ik heb er nog eens over nagedacht en ik zie niet in hoe we dit überhaupt zouden kunnen bouwen zonder de boel onwijs veel ingewikkelder te maken voor iedereen. De marginale gemakswinst voor onze Amsterdamse vrienden weegt daar m.i. niet tegenop. Daarom sluit ik dit issue.
