### ISSUE TITLE
Imported old sent newsletters do not show any content when selecting 'view in browser'

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#118]

**Comment by Pieter1024** [comment]
@trolando The content is all there in the database. However, no output is shown. I suspect that the content filtering may be set a bit too strictly.

**Comment by trolando** [comment]
Ha. No template is set, that will never work.

Set template to "{{content}}" and you will see "some" content. An alternative is to put everything in template. It will simply render all that with barely any processing, except for putting images embedded if you would choose to send old newsletters by mail.

The content is filtered using bleach with the following settings:
```
allowed_tags = ['a', 'b', 'blockquote', 'caption', 'code', 'em', 'h1', 'h2', 'h3', 'i', 'img', 'strong', 'ul', 'ol', 'li', 'p', 'br', 'span', 'table', 'tbody', 'tr', 'td', 'thead', 'div', 'span']
allowed_attrs = {
    '*': ['class', 'style'],
    'a': ['href', 'target'],
    'img': ['src', 'alt', 'width', 'height'],
    'table': ['border', 'align', 'cellpadding', 'cellspacing'],
}
```

The template is not filtered!!

**Comment by Pieter1024** [comment]
Great, thanks for sharing your thoughts, @trolando.

I would propose adding a template that contains {{ content }} and leaving the content in the content field. The data we import is not trusted, so I welcome any filtering you provide.

Should a random sample show that the content is mangled by the filtering, we can always decide to permit some other tags as well.

**Comment by trolando** [comment]
Or add the proper template that jnews uses....

**Comment by Pieter1024** [comment]
A possibility as well, definitely. It depends on how much information is actually stored in the content field, I guess.

**Comment by Pieter1024** [comment]
After trying a sample of old newsletters, I conclude that most of the content keeps working using the simple template. An example would be https://website.jongedemocraten.nl/nieuwsbrief/view/889/.
