### ISSUE TITLE
Separate departments should have separate websites

### ISSUE THREAD

**Issue by Pi2048** [jonge-democraten/website#12]

**Comment by bartromgens** [comment]
Ok. Clear. It's simply an external link. 

> The content we will ultimately provide on our production website is not a part of this repository.

True. However, there is a trade-off between a generic and abstract project and being able to develop and deploy with ease. Having some images in the repository, at least for now, is simply easier than creating a separate repository or method to get this content in a different way. 

I generally prefer to start with concrete implementations and move to abstraction if necessary.
We can easily switch to a more generic way where you set a header logo in the settings file. 

>  For example, do we really want to licence everyone to use our logo?

I personally don't see a problem with licensing the logo under MIT. What real harm can come from it?  
It's not for me to decide though and I did not intend to make the decision. The commit is easily reversible. Also in a legal sense. We can simply remove it or create a different licence for static content.

**Comment by bartromgens** [comment]
> The websites for the different department share the same server, VPS, Apache install, virtualenv and Mezzanine instance, but are logically entirely separated.

Just a note to self and others:
They also share the same database for Django apps.
