### ISSUE TITLE
Imported old (sent) newsletters do not retain their old publication date

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#121]

**Comment by Pieter1024** [comment]
This is due to a setting in the Newsletter model at line https://github.com/jonge-democraten/hemres/blob/master/hemres/models.py#L157. @trolando could you remove the auto_now_add setting and replace it with default = timezone.now()? We want to be able to set this date from the migration scripts.

Documentation about this setting is at https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.DateField.auto_now_add.

**Comment by trolando** [comment]
Fixed in next hemres version.
