### ISSUE TITLE
Hemres on the test website should be attached to the rq-worker

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#122]
As discussed on the phone with @trolando

**Comment by trolando** [comment]
Added the rqworker in /usr/local/bin and to monit.

Modified website local_settings to use database 1 of the redis server.

Should work, but did not test yet.

**Comment by trolando** [comment]
Reopen to allow for testing (sorry).

**Comment by trolando** [comment]
I have tested the functionality.

One problem was that I had to restart the rq worker before it accepted tasks. I do not know why it was stalled. I've modified the rqworker script to send all output to /var/log/website-worker.log so we can monitor it in that way.
