### ISSUE TITLE
Social media buttons on sites should be migrated

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#123]

**Comment by Pieter1024** [comment]
These are now included in the jd_finalize.py script. @miekedewit could you confirm that the social media buttons in the lower right corner of the departments' test websites look good and work?

**Comment by miekedewit** [comment]
@Pieter1024 

De facebookbutton gaat naar een verkeerde pagina, maar ik zag net dat dat ook op de oude website het geval is. Kan deze naar de pagina gaan (https://www.facebook.com/jongedemocraten)?

LinkedIn, Twitter en youtube doen het goed, ze zien er allemaal prima uit. (mooi effectje).

Wel zou ik liever zien dat de links openen in een nieuw scherm of tabblad, zou dat nog kunnen?

**Comment by Pieter1024** [comment]
Fixed link on the old website via Joomla admin. Fixed link on the new website in commit c01c5f9777ad48307f346959e789856a1b832c7a. Fixed open-in-new-tab on the new website in commit 93f776d9fdb7c7024f39a3127003bb51a7e27438.

@miekedewit does it look/work like you wanted it to?

**Comment by miekedewit** [comment]
Super!
