### ISSUE TITLE
Overview of newsletters published earlier

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#125]
The overview should match https://jongedemocraten.nl/component/jnews/mailing/archive/listid-1/listype-1/Itemid-342.html in broad functionality.

It should only list newsletters that are a) less than one year old and b) public.

**Comment by Pieter1024** [comment]
If I may be picky, I would like to have the url be /nieuwsbrief/list. I will create a link to this url in jd_finalize.

**Comment by trolando** [comment]
I'll add this soonish.

There would be an overview page that lists all Mailing lists that are publicly subscribable (i.e. there are no required janeus groups for subscription). 

From this overview page, every mailing list will have an overview page with a sorted list of earlier newsletters.

Do we need a search function and a "number of newsletters per page" functionality? I hope not, the number of visible newsletters per mailing list should be < 20 anyway, assuming they are only visible for one year, and there will be at most a monthly mailing list, plus a few mailing related to events such as the afdelingsvergadering?

For the URLS, may I suggest /nieuwsbrief/archive and /nieuwsbrief/archive/XXX/ with XXX the id of the MailingList in the database?

**Comment by Pieter1024** [comment]
Excellent, Tom. I think that's a sound approach.

Don't encumber yourself too much with nice-to-haves such as search. I think our volume doesn't require it.

The URL is fine either way. As soon as you decide upon it, I will change the link in jd_finalize.

**Comment by trolando** [comment]
There is now a list in /list.

Please check it out. Note that the dates are based on NewsletterToList date.

Also, check the last commits on Hemres. I changed the logic: no longer based on newsletter creation date, but on newslettertolist date. That "should" be a better approach, in my opinion.

**Comment by trolando** [comment]
It might be needed to "somehow" integrate this list with the proper JD pages template...?

**Comment by Pieter1024** [comment]
Cool, it looks great. I added a template for the listing. I do not think we should integrate the newsletters themselves in the template. Their fixed width, combined with the smaller fixed width of our content region, is bound to display their content poorly.

I consider this issue done, so I'm closing it.
