### ISSUE TITLE
Upgrade to Mezzanine 4.0.2 (was: Publishers get a 404 when trying to list all blog posts or events)

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#126]
This is understandable as they do not have the rights to view these listings. However, it is kind of odd given that the button for the listings is indeed visible to them. If possible, I would prefer removing the buttons on the left.

**Comment by Pieter1024** [comment]
Proposed approach is the same as I suggest in issue #119. Details can be found there.

**Comment by Pieter1024** [comment]
I think this is a bug in Mezzanine. I submitted a patch for this: https://github.com/stephenmcd/mezzanine/pull/1433.

**Comment by Pieter1024** [comment]
The pull request was accepted \o/. I guess it will be included in the next minor version.

**Comment by Pieter1024** [comment]
If we wish to resolve the issue manually before the next upgrade, we can apply the patch in https://github.com/stephenmcd/mezzanine/commit/1b2d96959f7bb400407d079d42fb5b6bef1540cf. I suspect the following upgrade will be available before the end of milestone 5.

**Comment by bartromgens** [comment]
> The pull request was accepted \o/

\o/

**Comment by bartromgens** [comment]
This is fixed with the upgrade to Mezzanine 4.1.0.
