### ISSUE TITLE
Import *all* old newsletters

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#127]
Most old newsletters actually have a list_id of 0 and are therefore ignored by our jd_finalize script. We should import these as well.

**Comment by Pieter1024** [comment]
There are only 35 newsletters in our test database that have list_id = 0 AND a subject that is not like '[JD %]%', so I think we can import the majority of the newsletters by adding them based on the prefix of the subject.

**Comment by trolando** [comment]
I already had the feeling there were really few newsletters in the system.

Might be an idea to generate the correct template for them instead of just {{content}}? Just put some HTML stuff around it, I think.

**Comment by Pieter1024** [comment]
Most of the template HTML is already in there, from the few samples I saw. No reason to any any extra.

**Comment by trolando** [comment]
Oh, the samples I saw start with a <p> instead of nicely opening with <html> and things like that. Are the mails sent like that in the old system? If so, we should get rid of it soon!

**Comment by Pieter1024** [comment]
I seem to have fixed the issue. The few (35, which is less than 4%) newsletters which remain are mostly test cases and newsletters that have been sent manually separately. If someone wants to check these by hand, be my guest. I'm closing this issue.
