### ISSUE TITLE
Social media sharing of content

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#13]

**Comment by bartromgens** [comment]
Here is the Facebook documentation for sharing articles that look good on Facebook, https://developers.facebook.com/docs/sharing/webmasters

There are currently 3 share buttons at the bottom of blogpost views. Facebook, Google Bookmarks(?) and Twitter. Have not tested any of them.

**Comment by Pieter1024** [comment]
* Introduced sharing buttons on event occurrences.
* Fixed sharing button for Google+ (used to go to Google Bookmarks?!)
* Fixed description and title fields so they appear in Twitter cards etc.
