### ISSUE TITLE
NewsletterToList date not set in migration

### ISSUE THREAD

**Issue by trolando** [jonge-democraten/website#131]
I think the actual date that the newsletter is sent (ie newslettertolist date) should be set in the migration. I changed the field from auto_now to default=timezone.now to allow this to be set.

**Comment by Pieter1024** [comment]
Isn't this set currently? I think that both the date of the Newsletter and the NewsletterToList are set to the max(create_date, send_date) of the mailing. This is to compensate for the fact that many mailings have a wrong date (1970) set for one of the two.

**Comment by Pieter1024** [comment]
Yes, line 338 and 346 of jd_finalize.py.

**Comment by trolando** [comment]
Ah then the next migration call will pick this up.

Op wo 14 okt. 2015 11:44 schreef Pieter1024 <notifications@github.com>:
