### ISSUE TITLE
Events sidebar redirects different

### ISSUE THREAD

**Issue by m-lies** [jonge-democraten/website#132]
Wanneer je via afdelingswebsite X, in de sidebar op "Bekijk volledige kalender" klikt word je doorgestuurd naar een activiteitenoverzicht van alle afdelingen. Wanneer je ditzelfde doet via de nieuwe site word je doorgestuurd naar een activiteitenoverzicht van enkel desbetreffende afdeling X.

**Comment by Pieter1024** [comment]
Dat klopt, dat is 'by design'. Mensen die op een afdelingswebsite kijken naar de kalender willen waarschijnlijk alleen de afdelings-events zien.

Zou het verduidelijkend zijn om onderaan de afdelings-agenda een link te plaatsen naar de agenda van alle afdelingen op de hoofdwebsite?

**Comment by m-lies** [comment]
Ja, dat lijkt mij wel overzichtelijker maar daar mag @miekedewit uitsluitsel over geven. Overigens, bij het activiteitenoverzicht van alle afdelingen op de hoofdsite staat onderaan een legenda met afdelingsnamen, voorheen waren dit links zodat je een apart overzicht kon krijgen van 1 afdeling. Is deze verandering ook 'by design'?

**Comment by Pieter1024** [comment]
Nee, dat hebben we gewoon niet gebouwd :). Dat is best een hoop gedoe om te maken, Ik zou zeggen 'de kosten wegen niet tegen de baten op'.

**Comment by m-lies** [comment]
Prima ;)

**Comment by Pieter1024** [comment]
OK ik heb een beetje gelogen over dat laatste, bleek na mijn laatste commentaar. Ik heb het inmiddels gebouwd. Het resultaat is te bekijken op de testwebsite.

Als we dit hebben, is het ook wel logisch om door te kunnen klikken naar de hoofdwebsite. Je komt dan namelijk op afdelingswebsites terecht waar je niet verwacht te zijn. Ik zal dat ook wel bouwen.

**Comment by Pieter1024** [comment]
@bartromgens I could use your help on getting my fix working. I made a commit (see above) that tries to include the link to the main site calendar. However, for some reason I can't access the {{ main_site_url }} tag from the context processor.

Could you look into this?

**Comment by Pieter1024** [comment]
Never mind, I fixed it.

@m-lies ik neem aan dat het zo goed is? Controleer het even. Als er verder niks is, mag je het issue sluiten.

**Comment by Pieter1024** [comment]
@miekedewit vindt het verder goed zo.
