### ISSUE TITLE
Add special page before migration: Word lid-formulier

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#134]

**Comment by Pieter1024** [comment]
Is het word-lid-formulier zo goed, @miekedewit ?

**Comment by miekedewit** [comment]
Wat ik nu kan zien ziet er prima uit, wordt het doorgestuurd naar de ledenadministratie?

**Comment by Pieter1024** [comment]
Log vooral in op de adminomgeving om de pagina ook daar te bekijken. Daar kun je alle e-mailadressen enzo instellen. Ik heb de waarden daar ingeschat, kijk ze vooral na en laat het weten als ze anders moeten.

**Comment by Pieter1024** [comment]
En het korte antwoord op je vraag: ja.

**Comment by miekedewit** [comment]
Ok! 

Is het mogelijk dat de blokken uitgelijnd worden zodat het er iets mooier uit ziet? Verder vind ik het goed zo.

**Comment by Pieter1024** [comment]
Moet wel te doen zijn ja, ik zal ernaar kijken.

**Comment by Pieter1024** [comment]
Hij is nu uitgelijnd. Ik sluit het issue. @miekedewit als het onverhoopt niet goed is kun je het natuurlijk heropenen.
