### ISSUE TITLE
piwik op nieuwe website laadt vanaf localhost

### ISSUE THREAD

**Issue by aprogas** [jonge-democraten/website#138]
Het Javascript-blokje voor Piwik onderaan de HTML-source van pagina's op de nieuwe website, bouwt de URL naar piwik.js op met `var u="//127.0.0.1/piwik/";` waardoor deze niet zal werken.

**Comment by Pieter1024** [comment]
Goed gezien! Dat was iets wat we blijkbaar waren vergeten in onze local_settings.py. Inmiddels is het gerepareerd.
