### ISSUE TITLE
Visitor cookie permission

### ISSUE THREAD

**Issue by aprogas** [jonge-democraten/website#139]
De oude website vraagt toestemming voor cookies en bijv. Piwik staat uit totdat deze is gegeven. De nieuwe website vraagt geen toestemming maar gebruikt wel cookies. Ik weet niet wat in de nieuwe versoepelde wetgeving de status van iets als lokaal draaiende Piwik is en of hier expliciete toestemming voor nodig is. Dus mogelijk werkt het nu al goed, maar misschien moet er toch een cookiebanner worden toegevoegd.

**Comment by Pieter1024** [comment]
Zeer waar dat hier aandacht voor nodig is. Gelukkig hebben we dit al besproken en afgehandeld in issue #5. Onder de nieuwe wetgeving is het niet nodig hiervoor toestemming te vragen. We willen wel graag instellen dat Piwik de 'do not track' header respecteert, maar dat is a) niet in scope en b) niet verplicht.

Ik sluit daarom dit issue weer.
