### ISSUE TITLE
Form to register as a member

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#14]

**Comment by bashazeborg** [comment]
Hi guys, 

Form is looking good! For some reason I do not see the CAPTCHA-form, only the field for entering the code. Is this correct?

**Comment by Pieter1024** [comment]
That is not correct. Let's look at why this happens on Sunday.

**Comment by bartromgens** [comment]
The CAPTCHA image is visible for me.

**Comment by Pieter1024** [comment]
To me too. Bas will look into this further on his instance. For now, closed as 'could not reproduce'.

**Comment by Pieter1024** [comment]
We found out the problem with Bas' deployment: you need to install libfreetype6-dev as a dependency.
