### ISSUE TITLE
Set a reasonable limit on size of uploaded documents

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#140]
Like 10 megabytes?

**Comment by trolando** [comment]
Probably fine, JD movies should go to Youtube anyway?

**Comment by Pieter1024** [comment]
This was something that was raised earlier today. As far as I can tell, the limit is 10 megabytes already (the documentation says so). I'll test this and close the issue.

**Comment by Pieter1024** [comment]
This already works.
