### ISSUE TITLE
Content managers should see the option 'send to list' in their Newsletter overview

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#144]
They currently only see 'View in browser' and 'Send test mail'

**Comment by trolando** [comment]
I found the error. In hemres/admin.py, line 55 checks for the wrong permission. The permission is tested at two locations, at line 55 to check if someone should see the link, and in views.py to see if the are allowed to execute the function. I modified the latter, but did not think about the check at line 55. Will fix.

**Comment by trolando** [comment]
Fixed in https://github.com/jonge-democraten/hemres/commit/ec06b59c485b6bd62e69285a0e54bfafacbf44de, moved tag 0.9 and updated on the live demo.
