### ISSUE TITLE
meer ruimte in vakjes landelijke agenda

### ISSUE THREAD

**Issue by miekedewit** [jonge-democraten/website#145]
In de agenda op de landelijke website passen max 2 evenementen, waardoor er wanneer er meer dan twee zijn de optie +2 extra komt te staan. Hierdoor lijkt het op het eerste gezicht (door de kleurtjes) dat sommige afdelingen geen activiteiten hebben. 

Kunnen de vakjes iets langer worden gemaakt waardoor er meer evenementen in passen? Dit is alleen voor de landelijke site, niet de afdelingswebsites.

https://website.jongedemocraten.nl/events/

**Comment by Pieter1024** [comment]
@miekedewit ik heb de vakjes nu zo aangepast dat er vier evenementen in passen. Deze maand betekent dat bijvoorbeeld dat op één dag na alle dagen groot genoeg zijn voor alle evenementen die erop vallen. Die ene dag (30 september) waren er zeven gelegenheden op een avond, het lijkt me wat overdreven om daar ruimte voor te maken.

Aanpassen voor de verschillende afdelingen zou weer wat extra moeite zijn, als dat niet zo nodig is laat ik het liever achterwege. Is het goed zo, wat jou betreft?

**Comment by miekedewit** [comment]
Super!
