### ISSUE TITLE
Subscribing for e-mail newsletter subscription yields error

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#146]
Steps to reproduce:

1. Go to homepage of main website.
2. Click 'Nieuwsbrief' tab. Enter e-mail address to request confirmation e-mail.
3. Click on link in confirmation e-mail.
4. Choose any newsletter, click save.
5. Error.

I think the problem arises because of this line: https://github.com/jonge-democraten/hemres/blob/master/hemres/models.py#L92. I can't decide whether I should add a tab (to put the s.save() in the scope of the for statement or remove the s.save() altogether.

@trolando could you fix this?

**Comment by trolando** [comment]
Nah it is a lot suffer. It should simply read "self" instead of "s".
