### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#147]
This is a 'should fix' when running Google PageSpeed Insights on jdwebsite. 

> Your page has 2 blocking script resources and 1 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Remove render-blocking JavaScript:

>    https://website.jongedemocraten.nl/static/mezzanine/js/jquery-1.7.2.min.js
>   https://website.jongedemocraten.nl/…atic/mezzanine/js/jquery-ui-1.8.2.min.js

> Optimize CSS Delivery of the following:

>    https://website.jongedemocraten.nl/static/website/css/template.css

Here is Google's howto: https://developers.google.com/speed/docs/insights/BlockingJS

**Comment by Pieter1024** [comment]
I added the 'async' attribute to the jquery script tags, to no noticable improvement. If anything, it slowed the page load times down. I may be missing something :).

**Comment by bartromgens** [comment]
It was worth a shot. Thanks for trying :) 
I don't think there is much to gain here, although I have no experience with website optimization, and I am fine with closing this issue.

**Comment by Pieter1024** [comment]
As we do not know how to further approach this, and it does not have any priority per se, I am indeed closing the issue.
