### ISSUE TITLE
Add description of twitter poll cron job to deploy/admin docs

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#148]
(/usr/local/bin/poll_twitter.sh) cronjob (/etc/cron.d/website-twitter)

Docs are at http://mezzanine.jupo.org/docs/twitter-integration.html?highlight=twitter.

**Comment by bartromgens** [comment]
I have added some instructions, see here: http://jdwebsite.readthedocs.io/en/latest/administrator/#deployment

That should be sufficient, but feel free to improve.
