### ISSUE TITLE
Broken link to TitleBackground.png 

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#149]
Many migrated pages use https://jongedemocraten.nl/templates/jd/images/TitleBackground.png in the style of a `<h3>`.

This file is now located at https://jongedemocraten.nl/static/website/images/TitleBackground.png

Can we easily fix this with a redirect? I have not used redirects yet. Can we simply add one via the admin interface?

**Comment by Pieter1024** [comment]
I have added a redirect to this effect. This can indeed be done from the admin interface.

Do you have an example page that uses such an <h3> style? Could you check whether it now works correctly?

**Comment by bartromgens** [comment]
It works! Thanks.

https://jongedemocraten.nl/politiek/ is an example. It is used in many migrated pages.
