### ISSUE TITLE
Migrated email links are broken

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#150]
For example, ict@jongedemocraten.nl on https://jongedemocraten.nl/contact/ links to https://jongedemocraten.nl/contact/&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#105;&#99;&#116;&#64;&#106;&#111;&#110;&#103;&#101;&#100;&#101;&#109;&#111;&#99;&#114;&#97;&#116;&#101;&#110;&#46;&#110;&#108;

Does anyone know what happened here? And how to fix this?

There are about 50 email links like this on the main site.

**Comment by Pieter1024** [comment]
What happened is our htmlentities-encoding to somewhat prevent spammers from harvesting the e-mail addresses. This was discussed in issue #49. Apparently, these specific links do not work properly. I'll look into this.

**Comment by bartromgens** [comment]
This is fixed in commit 4f7a3d339b813721f0da5216c97760065b72618f that removes email obfuscation.
