### ISSUE TITLE
Create Join Page

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#161]

**Comment by mathemaat** [comment]
Ik ben begonnen met de "Word lid" pagina, maar ik denk dat ik in de verkeerde richting bezig ben. Deze pagina heeft wel een speciale definitie, waardoor ik het idee kreeg om een WordLidPage te definiëren. Dat zou wel eens de juiste aanpak kunnen zijn, ware het niet dat ik ook geprobeerd heb om de tekst instelbaar te maken via het adminportaal. Ik heb hem nu toegevoegd aan het menu, maar dat lijkt me niet de bedoeling.

![afbeelding](https://user-images.githubusercontent.com/17109197/31049566-0c5e6a1a-a636-11e7-9b4e-0eb025361bfc.png)

https://github.com/jonge-democraten/website/tree/161-join-page

**Comment by bartromgens** [comment]
Als de pagina een speciale definitie heeft voor 'Word lid', lijkt me het maken van een WordLidPage de juiste oplossing. 

Op de admin van de pagina is een checkbox die aangeeft of de pagina zichtbaar moet zijn in het menu. Die moet je hiervoor dus uitzetten. Ook kan je in de 'Meta' sectie van de pagina admin een url instellen. 

Volgens mij zit je dus wel goed. 


De pagina heeft eenzelfde 'ActionBanner' als de homepage. Dat element kan je in de backend dus makkelijk toevoegen met een inline in de admin (voorbeeld: https://github.com/jonge-democraten/website/blob/5688bec99ea47d76b0170d231e1263ad10296bc3/website/jdpages/admin.py#L106). 
De template code (om te includen) vind je hier https://github.com/jonge-democraten/website/blob/161-join-page/website/templates/components/content/content_action_banner.html

De zogenaamde 'doe-mee-banner' (https://github.com/jonge-democraten/website/blob/161-join-page/website/templates/components/content/content_doemee_banner.html) is nog niet geïmplementeerd.
