### ISSUE TITLE
Remove twitter code

### ISSUE THREAD

**Issue by mathemaat** [jonge-democraten/website#203]
zie titel

**Comment by mathemaat** [comment]
Hey @bartromgens 

Kun je even meedenken? Hoe precies zouden wij de CSS van de Twitterfeed moeten nabootsen? De designer heeft hier natuurlijk niks voor gemaakt.

Als het één op één moet zijn, dan moet ik nog de volgende dingen doen:

- de icoontjes (svg images) overnemen
- de tijdsweergave fixen
- de profile images cirkelvormig maken dmv een border
- het lettertype achterhalen en overnemen

Vooral die bovenste twee punten lijken me veel/ingewikkeld werk voor weinig winst.

Dit is wat ik tot nu toe heb. De bovenste is mijn versie. De onderste is de originele Twitterfeed. Daar weer onder zie je hoe het in de huidige website is opgelost.

![afbeelding](https://user-images.githubusercontent.com/17109197/32194972-37b33b6c-bdbc-11e7-8e1b-9d976206d01c.png)

![afbeelding](https://user-images.githubusercontent.com/17109197/32195282-274e8942-bdbd-11e7-8dde-01a268554b74.png)

Wat zou je minimaal nog toegevoegd willen zien aan de versie die ik gemaakt heb?

**Comment by mathemaat** [comment]
Deze WIP-versie is eventueel uit te checken via branch 203-custom-twitter-feed.

**Comment by bashazeborg** [comment]
Als er problemen zijn bij de uitvoer van het design kunnen we ook de
designer nog om hulp vragen. Er zit wel enige nazorg in het contract
namelijk.


Met vriendelijke groet,

Pauline Gerth van Wijk,

Secretaris
Jonge Democraten



*T*: +31 (0)6 16327311
*E*:  secretaris@jongedemocraten.nl
*W*: www.jongedemocraten.nl



2017-10-30 21:58 GMT+01:00 mathemaat <notifications@github.com>:

**Comment by mathemaat** [comment]
Interessant dat Pauline actief is onder @bashazeborg . Is dat een account dat van secretaris op secretaris wordt doorgegeven?

@bashazeborg Welke zaken mis jij nog in mijn versie van de Twitterfeed? Denk aan acties als reply, retweet en favorite, zoals ook in de huidige site.

Als je mijn versie wat saai of bleekjes vindt, wat ik me kan voorstellen aangezien ik die kekke icooontjes van Twitter niet heb overgenomen, dan stel ik voor dat je de designer nog even inschakelt. Vergeet dan niet aan de designer het antwoord op bovenstaande vraag door te geven.

**Comment by bashazeborg** [comment]
Haha, ik kwam hierop omdat hij gekoppeld was aan het secretarismail, maar
ik moet zeggen dat ik alleen secretaris had gezien en niet bashazeborg.
Ach, ik kan ermee leven om als Bas door het leven te gaan.
Een mogelijkheid om te reageren op de tweets zou ik nog wel mooi vinden.
Verder vind ik het al heel mooi (zowel praktisch als esthetisch).

Met vriendelijke groet,

Pauline Gerth van Wijk,

Secretaris
Jonge Democraten



*T*: +31 (0)6 16327311
*E*:  secretaris@jongedemocraten.nl
*W*: www.jongedemocraten.nl



Op 31 oktober 2017 om 21:05 schreef mathemaat <notifications@github.com>:

**Comment by bartromgens** [comment]
@mathemaat Wat is de status van dit issue?

Lukt het om dit voor komend weekend af te krijgen?

**Comment by mathemaat** [comment]
@bartromgens 

De code was bijna klaar, dus ik had me voorgenomen het de 9e afronden. Bij nader inzien heb ik het nu maar vast even gedaan. Pull request is onderweg.

**Comment by bartromgens** [comment]
PR merged dus dit issue kan dicht.
