### ISSUE TITLE
Lookup layout of departments on interactive map

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#21]

**Comment by Pieter1024** [comment]
This page includes quite some JavaScript, including some external code. I would not like our Content Managers to be able to include such code arbitrarily.

Generally speaking, we can do two things:
* Make a page type that contains this code in the middle, with two rich text fields (one above it, one below it). Use this page type exactly once, namely on the departments page.
* Make an output filter that whitelists the exact JavaScript that is called on this page. This closely matches the solution we used in issue #28 for embedding YouTube videos.

I would prefer the second approach. It requires less code and is more transparent to the average Content Manager. Also, it is in line with an approach already followed before.

I welcome other thoughts on this matter.

**Comment by bartromgens** [comment]
I also prefer whitelisting (filtering) over a special Page type with hard-coded content in the template that is used only once.

The only issue with filtering I can think of is the performance. But it is probably very fast for most pages. No need for premature optimization.

**Comment by Pieter1024** [comment]
Whitelisting of script tags now works in the mentioned commit. I do not see the department map yet - will look into that. When that works, I'll add demo data and merge the code into master.

**Comment by Pieter1024** [comment]
Ah, it appears some files are looked up relative to the root in our JS file. From my logs:

```
[13/Jan/2015 01:08:27] "GET /word-actief/templates/jd/javascript/kaart/afdelingen.json/ HTTP/1.1" 404 11270
[13/Jan/2015 01:08:27] "GET /word-actief/templates/jd/javascript/kaart/gemeenten_2013.topo.json/ HTTP/1.1" 404 11287
```

To be fixed.

**Comment by Pieter1024** [comment]
This now works since commit 6e55d8b45100203df0c92d4ea5d0f8e1ef6440c6. I'm closing the ticket.
