### ISSUE TITLE
Re-reading old newsletters

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#24]

**Comment by Pieter1024** [comment]
@trolando , until how long ago are old newsletters readable? Would it be possible to make sure they are only readable until one year after publication?

**Comment by trolando** [comment]
It would be technically possible, but then features must be made that
regularly "cleanup".

**Comment by Pieter1024** [comment]
Why, though? Can't we just display a 'thank you for your interest, this newsletter is no longer available'-page if the creation/sending date of a newsletter is < 1 year ago? We can even redirect people to the correct functionary to get an archived newsletter sent to them.

**Comment by trolando** [comment]
Oh, yes, a timeout could be possible. I mean the "regularly cleanup" needs
a cronjob or something like that.

**Comment by trolando** [comment]
OK so then I propose adding a field "expiration" datetime field or
something like that, which replaces the "public" booleanfield. An expired
newsletter can not be viewed online, and the default "404" will contain
instructions for sending mails to a functionary.

**Comment by Pieter1024** [comment]
I think that is too much flexibility for the average user. Also, we need the 'public' field to distinguish between open and closed lists (e.g. department newsletter vs 'kader' newsletter).

I would put in a counterproposal:
* In settings.py, the admin can set an expiration time for all old newsletters. Default value is one year.
* When a user tries to open the newsletter on the website, we check whether current_time < publication_time + setting.expiration_period. If it is, give the newsletter. If it is not, give a 404 with instructions.

This is simple to use, enables privacy by default and is low-maintenance.

**Comment by trolando** [comment]
oki
