### ISSUE TITLE
Allow backend login of content managers (AS)

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#26]

**Comment by Pieter1024** [comment]
I feel content managers should have the same access as administrators, with the following exceptions:

* They can only access their own Site (not those of others).
* They cannot access the Site category of admin panels (i.e. Sites, Redirects, Settings)
* They cannot access the Users category of admin panels (i.e. Users, Groups)

In other words, content managers can do the following on their own Site:
* They can create, edit and remove content.
* They can create and delete pages and reorder their menus.
* They can upload and remove documents and images in the media library, for use in other content.

**Comment by Pieter1024** [comment]
Also, they should not be able to change the blog categories on their Site, as such changes have architectural impact (we link to blog categories, we use them for the structure of the front page, etc). Stuff could break if they willy-nilly changed those.

If they want to categorize stuff, they can use keywords in the metadata at the bottom. That is much more free-format and has much less impact upon structure and functionality.

Furthermore, I feel they should be able to change the structure of their own frontpage. After all, why else is @bartromgens making it so easy to do so? ;-)

**Comment by bartromgens** [comment]
That sounds good to me. 
I believe we should give them as much freedom as we can. But we should disable deletion and/or modification of some model objects that can break the website. Our backend testers will be useful to find the weak points.

**Comment by Pieter1024** [comment]
I propose to give content managers create/modify/delete rights on all but the following models:

* admin.* (log entries)
* auth.* (users, groups, permissions)
* blog.BlogCategory (as argued above)
* comments.* (we don't use comments, let's not confuse them)
* conf.* (settings: nothing for them to change, may break stuff or make stuff insecure)
* contenttypes.* (nothing for them to do there)
* core.* (sites functionality)
* galleries.* (we don't use galleries, we don't support galleries)
* generic.* (keywords, comments, ratings - we don't use them, let's keep it simple)
* jdpages.columnelement (we decide what elements may be added)
* redirects.* (not something for CMs to change)
* sessions.* (core functionality, not for CMs to mess with)
* twitter.* (we only suppor twitter feeds, and those are set in Settings)

As more models are added, this list is bound to change.

**Comment by trolando** [comment]
Fix ready in feature branch feature/janeus-integration/#26.

To assign content managers rights, create Janeus roles with the correct permissions.

**Comment by Pieter1024** [comment]
Such a group and janeus roles have been created:

* Group Content Managers contains the permissions of content managers.
* User cm has the group Content Managers for the main website.
* The group Content Managers was granted to janeus roles role-as-landelijk and role-as-leidenhaaglanden. They can be granted to janeus users to test this.
