### ISSUE TITLE
Content managers can modify content from the frontend

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#29]
Content = blog posts and static pages.

**Comment by Pieter1024** [comment]
For blog posts and static pages, this is already taken care of by default in Mezzanine. The way to extend this to other page types is described on http://mezzanine.jupo.org/docs/inline-editing.html.

Other types for which this may be relevant:
* Forms
* Events (up to @sh4wn )
* Document listings

**Comment by Pieter1024** [comment]
I propose we do this for events, but not for forms or document listings. It would add some complexity there, and it does not feel unnatural that you cannot change more complicated fields from the frontend.

**Comment by sh4wn** [comment]
Voor events is dit geïntegreerd in the details template.

**Comment by bashazeborg** [comment]
Checked this for events and it works fine. I agree with Pieter on not doing this for forms or document listings, so I guess this issue can be closed.
