### ISSUE TITLE
Uploading, renaming, moving and deleting files

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#30]
Voorbeelden: reglementen en congresboeken.

**Comment by Pieter1024** [comment]
The Mezzanine Media Library by default allows uploading a wide range of files, including .pdf and .doc.

My approach will be:
* Make sure it also allows .docx.
* Create a subclass of Page that provides a file listing.
* Make sure the admin interface of the file listing is usable.

Then, to display files on a website:
1. You upload the file through the Media Library.
2. You create a File Listing and attach it to a menu.
3. In this file listing, you include the file you uploaded.

**Comment by Pieter1024** [comment]
This issue is provided for in the Media Library. The question of Document Listings is discussed in issues #19 and #20.

More specifically, it is possible to upload, rename, move and delete files in the Media Library in the admin panel.

**Comment by bartromgens** [comment]
Very nice! I like how this works.
