### ISSUE TITLE
Create, preview, edit and publish events

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#31]
In a WYSIWYG editor, allowing for uploading of photos, links and embedded content.

**Comment by Pieter1024** [comment]
For embedding of videos, check the comments on issue #28 - those should work on your events too if you subclass them from Displayable and make the description a rich text field.

**Comment by m-lies** [comment]
Currently, when creating an event the 'add another' function (at the lower right) is not working. When you click on it, nothing happens.

**Comment by sh4wn** [comment]
Yeah I couldn't figure out why that button doesn't work. I believe I configured everything as it should be, but maybe I'm missing something?

**Comment by bashazeborg** [comment]
I works fine, I have one question though: the individual departments can choose between different colors to mark events. As the events off all the departments come together in the calender of the frontpage, this is not a desirable option. Every department should have one color which cannot be changed. Is this possible?

**Comment by sh4wn** [comment]
This is already the case: the choosen colors are only used in the department specific calendars, not in the aggregated calendar.

**Comment by sh4wn** [comment]
Furthermore, the colors for the departments can be set in settings.py. But you'll need to know the site ID used in mezzanine.

**Comment by Pieter1024** [comment]
@sh4wn I've fixed the issue with the 'Add another' link that @m-lies mentioned.

@m-lies, it is in the separate repository that @sh4wn uses for the calendar. I've updated your version on the VPS.

**Comment by Pieter1024** [comment]
From the discussion above, I conclude that this issue can be closed.

@sh4wn, if you do not agree, will you describe what things still need to be done for this?
