### ISSUE TITLE
Creating (not: sending) newsletters

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#33]

**Comment by Pieter1024** [comment]
There is no demo data yet (e.g. templates) for the newsletter functionality. This makes it very hard to demonstrate it.

**Comment by bashazeborg** [comment]
What is the best way to get this demo data? Is this part of the migration
Floor is working, something Tom can do on or should I make up some events?

Met vrijzinnige groet,

Bas Hazeborg

--

Landelijk Bestuur der Jonge Democraten
Algemeen Secretaris

Telefoon: 06 38977320
E-mailadres: secretaris@jongedemocraten.nl

2015-04-16 23:06 GMT+02:00 Pieter1024 <notifications@github.com>:

**Comment by Pieter1024** [comment]
This is up to Tom. It mostly amounts to creating a newsletter and some 
template for it.

**Comment by bashazeborg** [comment]
Tom is at a conference and tries to look at it tonight.

Met vrijzinnige groet,

Bas Hazeborg

--

Landelijk Bestuur der Jonge Democraten
Algemeen Secretaris

Telefoon: 06 38977320
E-mailadres: secretaris@jongedemocraten.nl

2015-04-17 14:57 GMT+02:00 Pieter1024 <notifications@github.com>:

**Comment by trolando** [comment]
I did many lookings and this is finished. Demodata is exist.
