### ISSUE TITLE
Links to the old website should keep working on the new website

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#4]

**Comment by Pieter1024** [comment]
@floort, we currently know very little about your progress.

Could you share your code in the repository and/or share some thoughts about your progress? Thanks!

**Comment by bartromgens** [comment]
I would also like to get an update on the joomla to django database migration, @floort.

**Comment by Pieter1024** [comment]
Most migration stuff is now working. The only big thing I can think of is the actual migration of old links, the aliases that used to work on the old site. We currently migrate the column 'link' as the old_url, but I think we should use the column 'path' instead. These are the links that are presented in menus, so these are the ones most likely to have been bookmarked/shared by people.

Furthermore, many of these old links do not work correctly yet because they are not linking to the appropriate subdomain.

**Comment by Pieter1024** [comment]
Also, redirects were not working because of a missing '/' at the beginning and end of the from_url. I fixed that.

**Comment by Pieter1024** [comment]
There sometimes is a prefix that is not taken into account. For example, when migrating 'http://jongedemocraten.nl/jdmedia/weblog/5467-jelle-ages-bescheiden-brutaaltje.html', the '/jdmedia' prefix is ignored.

**Comment by Pieter1024** [comment]
And of course, there's the rest category 'uncategorised' that is linked from the jdfryslan.nl website and so confuses the hell out of our import script :D

**Comment by Pieter1024** [comment]
[ ] Import prefixes
[ ] Redirect to proper department domain
[ ] Resolve 'uncategorised'
[ ] Import links from column 'path'
[ ] Include slash at beginning and end of from_url

**Comment by Pieter1024** [comment]
@floort and I just spoke on the phone about this issue. We concluded that to import *all* old URLs as redirects is a Lot of Work. If the need for redirects to old content is not that high, we can manually import redirects to all recent (< 1 month) content (blog posts, events). The old URLs would cease to work. The content itself would be findable through the search function on the site (which already works).

After that, I spoke with @miekedewit. She agrees that the main focus of this requirement is the recent past (and for events, the near future). Breaking URLs of old content is not that much of a concern. She finds a manual approach upon migration acceptable. I will prepare a spot for this information in the jd_finalize.py script.

**Comment by Pieter1024** [comment]
The spot is prepared. The manual import should be prepared in the deployment guide, which is issue #74. Other than the content of that issue, we are done here.
