### ISSUE TITLE
Tracking with Piwik Analytics

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#42]

**Comment by bartromgens** [comment]
We decided that Piwik should work for different sites/departments. 

Bas can give me a login for Piwik.

**Comment by bartromgens** [comment]
Piwik tracking for each site/department is implemented in commit 5dedaeecbc162a2fee437aa390c048eda2fa18d7

- A tracking code is added to the desktop and mobile base.html template.
- The Piwik URL (for example, www.jd.nl/piwik) is set in local_settings.py.
- Each site/department has its own Piwik site ID, which can
be set in the admin (Site->Settings->Piwik site id), that corresponds with a 'Website' within Piwik. 

I installed Piwik locally following [this](https://www.howtoforge.com/how-to-install-piwik-on-ubuntu-14.04) guide to test it. Works fine for multiple sites. 

When the site is deployed, a new 'Website' should be created in Piwik for each department, and the corresponding site ID should be set in the department site admin.

**Comment by bartromgens** [comment]
Note that no tracking code is included in the template when `PIWIK_URL` is empty or not defined in `local_settings.py`.
