### ISSUE TITLE
Search engine on website

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#43]

**Comment by Pieter1024** [comment]
The documentation is at http://mezzanine.jupo.org/docs/search-engine.html.

**Comment by bartromgens** [comment]
I added a search field and button, and a search results page. In jd.nl style using the Mezzanine search engine. 

![jdsearch](https://cloud.githubusercontent.com/assets/2451596/8190658/4f1b9c08-1464-11e5-9ad5-2a64d51d2d6d.png)

The models to be searched are defined in settings.py, 
`SEARCH_MODEL_CHOICES = ('pages.Page', 'blog.BlogPost', 'events.Event')`.

So currently all Pages (and derived models), BlogPosts and Events can be searched.

See commit 2c04a7fd726cc63470d602cef42589ff980cdfc5.

**Comment by Pieter1024** [comment]
The mobile template does not include a search field (= same as original website behaviour).

When viewing a search results page on a mobile agent, the regular template is used (because there is no mobile template for this type of page).

I find this acceptable because it is the same as on the original website. @bartromgens, are you aware of this and do you feel the same?

**Comment by bartromgens** [comment]
I was aware of this and had the same thought. 

There simply is no search functionality on the mobile website, so also no need for a search_results mobile template.
