### ISSUE TITLE
Implement a caching mechanism

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#44]

**Comment by bartromgens** [comment]
We use basic Mezzanine caching via the `MIDDLEWARE_CLASSES` in settings.py: `mezzanine.core.middleware.UpdateCacheMiddleware` and `mezzanine.core.middleware.FetchFromCacheMiddleware`.

This is likely sufficient. I think we should test performance on a production instance before we add any additional caching.

**Comment by bartromgens** [comment]
We would need to setup Memcached if we want real cross-process caching. However, I there are no known performance issues, so there is no need to introduce this extra complexity.
