### ISSUE TITLE
Website should support extensive error reporting

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#45]
With stack traces, for example.

**Comment by bartromgens** [comment]
At the moment we have,

* `django.log` contains stack traces for Django errors 
* `error.log` contains jdwebsite error log statements
* `debug.log` contains jdwebsite debug log statements

Max log file size is 10 MB. Last 3 files are kept.

**Comment by bartromgens** [comment]
Errors, including stack trace, are send via email to all admins (as defined in the ADMINS setting) with commit a5deadf429d3fd79964d669bc151c0e1d87bd87e.

The admins and outgoing email settings are defined in `local_settings.py`. I tested the email error notification locally. Works as expected.

I believe we now have proper and extensive error reporting available.
