### ISSUE TITLE
Escaping email addresses using Javascript

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#49]

**Comment by Pieter1024** [comment]
I have chosen this approach based on the discussion on https://stackoverflow.com/questions/748780/best-way-to-obfuscate-an-e-mail-address-on-a-website, but I welcome other views. There, people argue that spam filtering works better than e-mail address hiding, and I'm inclined to agree with them. This approach will stop the basic attacks, and spam filters will hopefully work against the more sophisticated ones.

**Comment by bartromgens** [comment]
I also agree that we should mainly rely on spam filters. It's simply not possible to fully hide email addresses for crawlers in a user friendly way. I believe many of the public jd email addresses are already out in the open so we need good spam filters anyway.

The obfuscation you added in commit cb3bd219b7ed6c97d67293d5bccd89dd8ec18569 is a good first line of defence.

**Comment by Pieter1024** [comment]
@bartromgens, thanks for giving your view.

Merged the branch for now. I'll leave it to Bas to evaluate the functionality. To me, this issue is closed for now.

**Comment by bashazeborg** [comment]
Agree with the discussion in https://stackoverflow.com/questions/748780/best-way-to-obfuscate-an-e-mail-address-on-a-website. When using spamfilters there is a good protection and a userfriendly way, so according to me a good option.
