### ISSUE TITLE
Embedded video should not store cookies

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#5]

**Comment by bartromgens** [comment]
I am not able to do this within the coming week(s). Although this is a 'must' and the header images are a 'should', I feel more like working on the headers right now (selfish argument).

I see no problem to get this to work before milestone 4. 

@Pieter1024 or others, feel free to take this one if you want.

**Comment by bartromgens** [comment]
Mezzanine does not place any cookies. Only the normal Django authentication cookies. 

If we only have authentication and analytics cookies, we don't need a cookie notification according to Dutch law. 

Is there still a reason to have a cookie notification? 

Embedded YouTube videos seem to place cookies.
Does anyone know more about this? I'm not familiar with cookies and cookie laws, so I would like some help here.

**Comment by Pieter1024** [comment]
You are absolutely right. We do not need a cookie notification after the recent amendment to the Telecommunications Act. More information is available at https://www.acm.nl/nl/publicaties/publicatie/13987/Veelgestelde-vragen-over-de-cookiebepaling/.

It would be nice if Piwik Analytics did respect the do-not-track HTTP request header, but that is out of scope of this project.

We are currently looking into the cookie behavior of YouTube. This is the only remaining issue, we will probably not need a cookie notification.

**Comment by Pieter1024** [comment]
Following the above discussion, I also removed the cookie notification from the mobile template. See issue #50 for details.

**Comment by Pieter1024** [comment]
Also, after the change in focus of this issue, I feel we can safely change it to milestone 5. We will not embed a lot of video on our site.

**Comment by Pieter1024** [comment]
We should wrap embedded video in a permission wrapper: first, give permission to store cookies and *then* view the video.

**Comment by Pieter1024** [comment]
I fixed this for YouTube video in the aforementioned commit. For other video providers, we will probably need a different approach as they do not have a -nocookie.com domain.
