### ISSUE TITLE
Provide website in mobile template

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#50]

**Comment by Pieter1024** [comment]
Development of the mobile template is mostly done. It has been included in the master branch with commit 416bfb2e659e799a24c7e8a1820f2ca0ab5ee7f2.

Things that still need to be done:
* Display headings (waiting for main layout to support them).
* Display upcoming events (waiting for work of @sh4wn).
* Make available under m.jd.local (not sure how to do that yet).

**Comment by bartromgens** [comment]
Looks great so far! Good job! 

I will probably do some more serious testing with the mobile site once the above mentioned points are implemented.

**Comment by Pieter1024** [comment]
In bd46ec135e4f7d088b6cf1bbc1422a146b479699, I changed two things:

* I removed the cookie notification (following the regular template).
* I added headers to mobile page types Page and RichTextPage. Other page types should be added as well (but the same holds for the regular templates).

**Comment by Pieter1024** [comment]
Things that still need to be done:
* [ ] Display headings (waiting for main layout to support them).
* [ ] Display upcoming events (waiting for work of @sh4wn).
* [ ] Make available under m.jd.local (not sure how to do that yet).
* [ ] Make mobile template for events templates.

**Comment by Pieter1024** [comment]
I propose to not have a separate URL m.jd.nl for the mobile website. In the future, we will have the department websites under separate domain names amsterdam.jd.nl, rotterdam.jd.nl, etc.. Having separate mobile websites complicates this further: will we have m.amsterdam.jd.nl?

I think user agent recognition works OK.

**Comment by Pieter1024** [comment]
One more:

[ ] Make mobile template for blog post detail
