### ISSUE TITLE
Look, layout and format of original website

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#54]
Create Django/Mezzanine templates that create the original jd.nl look, layout and format.

**Comment by bashazeborg** [comment]
Ziet er goed uit Bart, precies hetzelfde wat ook de bedoeling was. Ik zie wel verschillende lettertypes (bijvoorbeeld bij blog) maar ik ga er vanuit dat dit in dit geval zo hoort en het in de adminpagina zelf aan te passen is?

**Comment by bartromgens** [comment]
I did not finish the blog and blogpost templates yet. Still a work in progress. I will take many small step to make all details look exactly the same, but I think we can do them in small steps.

**Comment by malupasman** [comment]
Another something to fix has to do with the Social Networks section in the right hand column. In the as-is situation, every JD department has got its own format. E.g. JD Amsterdam has got the format 'JD Amsterdam Online Netwerken (see: http://jongedemocraten.nl/amsterdam.html), whereas JD Leiden-Haaglanden is using the format JD Leiden-Haaglanden Online (see: http://jongedemocraten.nl/leiden-haaglanden.html). 

In the to-be situation, we would like to use the same format for every department (JD *Department Name* Online). Every department should be able to choose the departments to appear, but we should disable the possibility to create different formats.

**Comment by Pieter1024** [comment]
I believe aligning images or text does not work currently - not sure what CSS prevents this.

Steps to reproduce:
* Select the paragraph and right click/right click on the image.
* Choose Alignment -> Center.
* Note that the paragraph/image is still left-aligned.

**Comment by Pieter1024** [comment]
Are header images indeed something we wish to set per page? I see many departments currently have random headings (jd.nl, jdfriesland.nl, jdamsterdam.nl (only 1), jdlimburg.nl (only 1)). I have found only one department with fixed but different headings per page: jdutrecht.nl. Perhaps we can persuade them to accept random headings as well? This would make the models less complex (i.e. we would currently not need a JDpage type).

**Comment by bartromgens** [comment]
@malupasman Good observation about the social media button section in the sidebar. This should be customizable per site. I made a new issue for this, see https://github.com/jonge-democraten/website/issues/60.

**Comment by bartromgens** [comment]
> Are header images indeed something we wish to set per page? I see many departments currently have random headings (jd.nl, jdfriesland.nl, jdamsterdam.nl (only 1), jdlimburg.nl (only 1)).

jd.nl has specific header images for different pages. Sometimes a page specific random set of images, for example http://jongedemocraten.nl/word-actief/word-lid.html.

We can create a backend editable header object that shows either a single image, or a random image from a set of images. This object can be inlined in the page admin. 
There should also be an option to show the parent page header.
 
Should we use the media library to store the images?

> This would make the models less complex (i.e. we would currently not need a JDpage type).

True. JDPage can be removed. I plan on doing this. We may need a custom page type in the future, but we can create one when we need it. It's easy to remove or add at this point. 

I believe https://github.com/jonge-democraten/website/issues/6 is the issue for the page header image, right?

**Comment by Pieter1024** [comment]
You are right. Way to support weird functionality, JD :).

OK, given that we want this, I think your approach is the nicest one. Each department then has one or more header objects. One of these is the default. On a per-page basis, you can select which header object you wish to use.

The advantages are:
* It supports all use cases that are currently applied.
* It minimizes complexity for those departments that want just one header image (they set that image in their header object and are done with it).
* It minimizes complexity for those departments that want to rotate through the same images on all their pages (they set those images in their header object and are done with it)..
* It allows to reuse images in several header objects (instead of having to copy them).

How do we approach caching in this case? I have some ideas, but my experience with caching is so limited that I'm afraid I will sound silly :).

**Comment by bartromgens** [comment]
> Each department then has one or more header objects. One of these is the default.

Yes, that would be nice. 
* Editable site-wide header objects (image, random image)
* A default header object can be set (and unset, meaning no header by default).
* Each page has an optional header that overrides the default

> How do we approach caching in this case? 

I have no experience with caching so you can sell me anything ;)

**Comment by Pieter1024** [comment]
I have worked on the mobile template (as described in issue #50). It is now available in master.

Please note that the mobile template sometimes includes elements from the regular templates. If you change them, be sure to check that the mobile template still works as well.

**Comment by bartromgens** [comment]
I believe most (all?) of the 'must' parts of this rather general issue is done, mostly in separate issues.

The remaining issues are ideally split into new separate issues for milestone 4.
I will try to do this within the next few days if there are no objections.

**Comment by Pieter1024** [comment]
To me, it is mostly important to know *which* issues are still open in 
this, admittedly, broad topic. If you could make a list, I would gladly 
contribute. I agree that it should easily be doable within milestone 4.

**Comment by bartromgens** [comment]
Yes, making a list of which issues are still open is the important and most difficult part. I will make a list.

**Comment by Pieter1024** [comment]
If @bartromgens indeed would make an issue for each remaining point, I feel confident I can close this broad issue.

**Comment by bartromgens** [comment]
Ok, good. I have gone through the different pages of the current website and made new issues for each remaining point that was not yet covered. 
Most important open issues are the blog templates and the department logos.
