### ISSUE TITLE
Database migration files during development

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#55]
I suggest to reset database migration files after initial development is done. That is, before we have a live database. 
We can already do this reset during initial development if it becomes a performance issue during database creation. 

If nobody objects, this means that migration files can, for now, be seen as temporary so that there is less reason to limit their numbers and keep them clean and independent. 
That is, at least as long as we solely rely on the demo_data fixtures that can re-create the database at any moment from scratch.

**Comment by Pieter1024** [comment]
I believe that we already discussed this 'issue' and decided to indeed consider these migrations as temporary. We may squash them, we may generate new ones, but the ones we have now will not be the definitive ones.

**Comment by bartromgens** [comment]
Ok. Good!
