### ISSUE TITLE
Bleach not in requirements.txt

### ISSUE THREAD

**Issue by trolando** [jonge-democraten/website#57]
following README.md, error: bleach not there. Should be in requirements.txt

**Comment by floort** [comment]
Bleach is a (sub?) dependency of one of the packages in requirements.txt and installs just fine for me with 'build_env.sh'.

**Comment by Pieter1024** [comment]
For me too.

**Comment by trolando** [comment]
Solved for me, turns out the issue was caused by a botched build_env.sh
after libpython3-dev was missing from my Ubuntu system. So: if build_env.sh
fails due to missing libraries on the system such as libpython3-dev, then
clean_env must be run first.
