### ISSUE TITLE
Document Listing should give visual feedback when adding files

### ISSUE THREAD

**Issue by m-lies** [jonge-democraten/website#64]
Been trying to upload documents in 'Add Document Listing', the documents are not shown when I click on 'select'. Disabled AdBlockerPlus and tried in Firefox and Chrome. Basically, nothing happens. 
Furthermore, there is an option to add another field to upload an extra document. However, it is not possible to delete a field if it remains empty. You seem to be only able to delete a field if there is already a document uploaded.

**Comment by Pieter1024** [comment]
Both these issues stem from the same problem: Document Listings do not give visual feedback when you've added a file. I'll look into this.

**Comment by Pieter1024** [comment]
I was not able to change this behaviour without changing the Mezzanine/Filebrowser-safe code. I will send an e-mail on this subject to the mezzanine-users mailing list.

**Comment by Pieter1024** [comment]
We got a reply: https://groups.google.com/forum/#!topic/mezzanine-users/cmcu39K8K8U.

It appears this was actually a bug in filebrowser-safe. They fixed it now. This means a new version of mezzanine will not have this problem. The commit (https://github.com/stephenmcd/filebrowser-safe/commit/0f53f3742abf00c18e14b1ad4ad2da5369586c03) contains pointers on how we can fix that preliminarily in our own project.

I'll apply their fix and then see how we can apply the thumbnail approach to document_listings. I expect we will pre-define some thumbnail that is used for all documents.

**Comment by Pieter1024** [comment]
I tested it and it works. In document_listings, you will now see a broken thumbnail with a link to the selected document. I will find some image to use as default thumbnail for documents.

**Comment by bartromgens** [comment]
Again good to hear this is fixed so quickly.

Also good job on reporting this issue Pieter. As developer, I like users who report issues. Most are simply too lazy. Others think it is some kind of negative feedback that is rude. They say things like 'sorry, but this does not work'.  Any good developer welcomes bug reports. It's a compliment that someone uses your work and wants to make it better.

**Comment by Pieter1024** [comment]
The aforementioned commit should resolve this issue. When a user now selects a document, the help text 'Document selected' is displayed.
