### ISSUE TITLE
Customizable blog listing per department

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#66]
Blogs are for a large part handled the Mezzanine blog app. See issue #15.

However, the Mezzanine blog view has several limitations/disadvantages,

* Creating a new blog listing page is not intuitive; you have to create a RichTextPage with a URL to the blog view. 
* The URL of this RichTextPage becomes hidden when a blog is found for the URL. This may be confusing and makes it impossible to change the blog/URL from the backend.
* The RichtTextPage is redirected to a Mezzanine blog view. This removes the option to use a Mezzanine page processor on the page.
* The blog listing page cannot be customized by a content manager. This means no header image, no number of posts setting, and no other blog listing specific settings in the backend.

To remove these limitations, while keeping the advantages of the Mezzanine blog app, I propose to create a new Mezzanine Page type for blogs. A blog page is a simple page with the following extra options that can be set in the admin,

* A blog category.
* A customizable header image, just like the other pages.

The Mezzanine blog view functions can still be used to generate the blog view context, but we can now also extend it. Same goes for the blog listing template. 

Optionally, we can add other properties to the blog page. Examples are the number of posts to show, and whether to show the full posts or just details with a 'read more' link.

This setup easily allows for future extension of the blog section of the site, without adding much complexity.

**Comment by Pieter1024** [comment]
Good idea. Make sure this also works for the mobile template.

**Comment by Pieter1024** [comment]
Isn't this also an issue for other page types, like events overview?

**Comment by bartromgens** [comment]
Yes, it is. If we want to customize specialized pages, like events and blog, via the backend/admin, we need to make it a new Page type. It is an easy and powerful concept that we can and should use if applicable; when we need a customizable specialized page.

**Comment by bartromgens** [comment]
I commented on the blogpage in issue #70. Should probably have been in this issue. 
I think I'll close this one and use #70 for remaining blog related discussion and updates.
