### ISSUE TITLE
Provide a street map with events

### ISSUE THREAD

**Issue by m-lies** [jonge-democraten/website#69]
Event descriptions currently have the nice feature of a street map.
For example: http://jongedemocraten.nl/component/jevents/icalrepeat.detail/2015/03/30/5228/-/debat-internationale-politiek.html?Itemid=0

**Comment by Pieter1024** [comment]
Put this in milestone 4 as adding a location to events changes the database structure. We would like to avoid changing the database structure after launching the website.

**Comment by sh4wn** [comment]
Added a map to the detail view using Leaflet widget.

**Comment by m-lies** [comment]
Events no longer shows a map on the front-end, somehow the Leaflet widget is no longer functioning. Therefore I'm reopening this issue.

**Comment by sh4wn** [comment]
Yeah there are some issues now with cross origin requests which didn't happen earlier, I'll look into that.

**Comment by sh4wn** [comment]
This is fixed in commit b271684bdccd1cca0f4686559ab4b219b7c44997
