### ISSUE TITLE
Calendar overview does not have a legend

### ISSUE THREAD

**Issue by sh4wn** [jonge-democraten/website#73]
When viewing a calendar, there is no legend telling giving meaning to the different colours used in a calendar.

**Comment by sh4wn** [comment]
This is partly fixed in commit c05e20e7195335867b77fe6522f41026d4d46e49. Still one thing: the legend is currently also shown on department sites. Is there any way to check in a template what the current site ID is, so we can hide it if it's not the main site?

**Comment by Pieter1024** [comment]
Hi @sh4wn,

The 'normal' way of doing this is including the check in the view you use to display the legend. An example is available at https://github.com/jonge-democraten/website/blob/master/website/templates/elements/tabs_sidebar_item.html#L16-L22. In other words, if the site is not the main site, just return an empty legend.

An alternative is to expose the site ID explicitly to the template by creating a template tag. This, however, seems to me to be the more 'hackish' approach.

**Comment by bartromgens** [comment]
Fixed in mezzanine-fullcalendar by only returning a legend when it is the main site, in the same way this is done in `views.py` of mezzanine-fullcalendar. Use the fix in commit eabae92f563822a69bf2fe8ce19c7a3e11f1890d
