### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#75]
Django 1.8 was released on April 1, 2015: https://docs.djangoproject.com/en/1.8/releases/1.8/

It is a long-term support (LTS) version, with security updates for at least 3 years. 

The Mezzanine readme was changed 2 days ago and now says it supports Django 1.8, https://github.com/stephenmcd/mezzanine/commit/135d41f9078c49140dfebdfc61fe14ba76e7a67b. 

I suggest we switch to Django 1.8 once Mezzanine supports it in a new release. We have plenty of time to test it now, and we need to test everything anyway for our first release. 

Any thoughts, objections or concerns?

**Comment by bartromgens** [comment]
Note that the Django 1.8 support is for the next Mezzanine release. 
Also see the discussion here, https://groups.google.com/d/msg/mezzanine-users/_QWfFVB3RVc/QIwq3jU2MsMJ, 

>I'm currently getting an error with the `createdb` command against 1.8 (but not 1.7) - if anyone wants to try and work that out it'd be awesome.

>Again, could *really* use help in testing the current dev branch against Django 1.7 and 1.8 - let's get this next release bullet proof against them!

> Once the above is sorted, I'll release the official new version, supporting Django 1.7 and 1.8. Perhaps we'll call it Mezzanine 4 rather than 3.2, it feels large enough to warrant a magical bump in the major version number."

We could help Mezzanine a bit and test the latest against Django 1.8. I will give it a try.

**Comment by trolando** [comment]
I encourage it, but cannot assist at the moment.

**Comment by bartromgens** [comment]
Note that I upgraded to Django 1.7.8 in commit 19f0a2d7fb5a5fb0e8bcd5731be131fdd62b6aac.

**Comment by trolando** [comment]
We should upgrade Mezzanine also? Mezzanine current release version is 4.0.1.

**Comment by Pieter1024** [comment]
I would love it if we could make our website work on Django 1.8 + Mezzanine 4.0 before going live. This would ensure a much longer support period before large changes are necessary. Given the level of knowledge that remains in the team, it is much preferable to not plan any large reprogramming responsibilities soon.

**Comment by bartromgens** [comment]
I am also in favor of upgrading to Django 1.8 + Mezzanine 4.0.1 as soon as possible. Before going live and before (more) testing.

**Comment by Pieter1024** [comment]
Why the preference for 'before more testing', @bartromgens ?

**Comment by bartromgens** [comment]
Because we may find issues related to the new versions. Not suggesting to postpone testing. Just to upgrade as soon as possible, not after most testing and bugfixing is done.

**Comment by Pieter1024** [comment]
OK, I seem to be the goto guy for "let's just upgrade and see what goes wrong", so I just upgraded. It all seems to kinda work.

My first attempt is at branch django-1.8. Please feel free to download and tinker. I have hardly tested it beyond 'it runs the demo data!'.

**Comment by Pieter1024** [comment]
Something to keep in mind (from the Django 1.8 release notes):

Support for MySQL versions older than 5.5¶

The end of upstream support periods was reached in January 2012 for MySQL 5.0 and December 2013 for MySQL 5.1. As a consequence, Django 1.8 sets 5.5 as the minimum MySQL version it officially supports.

**Comment by Pieter1024** [comment]
Just for fun I put the django-1.8 branch on the test server. It seems to be doing quite OK.

A few things I noticed:
* TinyMCE editor seems absent/broken
* Collapsing of TabularAdminInline (or whatever) seems broken
* Collapse submenus under tab Pages does not work

Other than that, it looks great!

I'm just going to leave it at django-1.8. Should that be a problem for you, the right steps to return to master are:

* Drop all tables in the MySQL-database jdwebsite. manage.py flush is not enough: the tables themselves have to go. Alternatively, drop the database and recreate it (command is 'CREATE DATABASE jdwebsite DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;')

* Check out branch master: 'git checkout master'. Perform a 'git pull' if necessary.

* Deactivate any virtualenv you may have running: 'deactivate'.

* Run './migrate.sh', followed by 'pkill -HUP -u website uwsgi'.

**Comment by trolando** [comment]
Did you also upgrade Mezzanine to 4.0.1?

**Comment by Pieter1024** [comment]
Yup

**Comment by trolando** [comment]
TinyMCE werkt niet omdat jQuery niet geladen wordt. De versie is bij de nieuwe Django/Mezzanine anders.

**Comment by trolando** [comment]
oh. umask 022 && website/manage.py collectstatic = win

**Comment by bartromgens** [comment]
Great. It looks good and seems to work without problems after some basic testing.

**Comment by Pieter1024** [comment]
I merged branch django-1.8 into master and deleted branch django-1.8, as there did not seem to be any reason to continue separate development. The test server now also runs master again. Any remaining problems should be filed as separate issues.
