### ISSUE TITLE
Registering and unregistering for the newsletter via the front page.

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#8]

**Comment by trolando** [comment]
Partially done, I am running into some trouble.

Hemres uses django-recaptcha. Website uses django-simple-captcha. Both have same package names in python. Before I can proceed, I need to remove django-recaptcha support from Hemres and somehow figure out a neat way to do use simple-captcha. Or something.

The new repository "hemres" contains sufficiently implemented support at least for this issue (registering, unregistering) and most of the support for writing newsletters and converting templates to email messages that can then be sent.

Open question: I want to make a form in the sidebar. How do I do this? If unanswered, the default option will be to link to the "main" page of hemres. The sidebar will then simply show the link, probably to "www.example.org/nieuwsbrieven" or something like that.

**Comment by bartromgens** [comment]
> I want to make a form in the sidebar. How do I do this?

Can you be more precise? What exactly do you want to know about adding a form in the sidebar?

**Comment by trolando** [comment]
This basically works, except I did not yet add a captcha. Should we do this? Maybe in the future. Closing for now!
