### ISSUE TITLE
Who broke the build?

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#84]
The build has been broken since a few commits by @trolando (see https://github.com/jonge-democraten/website/commit/7ae2c50109098c6efff91aa528c147781ed07446 for first broken commit).

Pulling the latest commit and building it gives me the same error as Travis gets: "No module named 'html2text'".

@trolando, could you fix this?

**Comment by Pieter1024** [comment]
In order to be able to work, I reverted @trolando 's changes in master and stored them in the separate branch oops/breakingstuffisbad.

**Comment by trolando** [comment]
Im on it. Gek.
Op 4 mei 2015 22:53 schreef "Pieter1024" <notifications@github.com>:

**Comment by bartromgens** [comment]
Breaking requirements like this is expected to happen. No problem if they are fixed right away. 

Here is our travis build history https://travis-ci.org/jonge-democraten/website/builds in case you want to check if it still builds on a clean machine.

I can add an email address (public in the travis config file) for build failure notifications. If anyone wants to be notified, just let me know.

**Comment by trolando** [comment]
It's fixed now. Checked with our friendly Travis.

**Comment by trolando** [comment]
Also, be excited about the new demodata, which includes some Hemres demo ;)
