### ISSUE TITLE
Events hebben geen veld voor lokatie

### ISSUE THREAD

**Issue by floort** [jonge-democraten/website#87]
Voor de functionaliteit van de kaart en ical exports hebben events een veld nodig voor de lokatie van het event.

**Comment by Pieter1024** [comment]
Volgens mij hebben Occurrences (= momenten waarop een event plaatsvindt) wel degelijk een locatie. Zie ook https://github.com/jonge-democraten/mezzanine-fullcalendar/blob/master/fullcalendar/models.py#L201. Wat je exporteert in iCal is de Occurrence, niet het Event.

**Comment by Pieter1024** [comment]
Draai je de site met de demo-data, dan is een voorbeeld van een kaartje te vinden op http://jd.local:8000/events/event/alpha-testing/5/.

**Comment by floort** [comment]
Je hebt gelijk. Faal met grep van mijn kant.
