### ISSUE TITLE
Versioning proposal

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#88]
I propose the following version scheme for the project,

| 1.3.9 | N.N(.N) | major.minor.micro |
| ------|:-----:| -----:|

* **major** release for everthing worth a new number
* **minor** release for all functional and model (database) changes
* **micro**(optional) release for bugfixes and minor view/template modifications 

Pre-releases get a suffix ,

|1.3.9a1| N.N.N(a/b/rc)N |alpha/beta/release-candidate |
|-------------|:----:|----:|

Versions are added as git tag.
I plan to make a first alpha release when we have our initial code stable,

**1.0a1** ?

**Comment by Pieter1024** [comment]
Excellent proposal!

**Comment by bartromgens** [comment]
I added this version scheme to the developer documentation in commit d82902a91870a44492bbd5cada4791c879ddc4c3.
