### ISSUE TITLE
Use case for event categories?

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#89]
@sh4wn, @Pieter1024, @bashazeborg, why do we have an event category?

'Event category' is an optional field when I make a new Event. Makes me wonder what it does. 
We already have Event and Occurrence. It should be as simple as possible for content managers. 

What is the use case for event categories?

**Comment by Pieter1024** [comment]
@sh4wn built event categories into the first version of full calendar. We then conckuded, like you do now, that this was unnecessary complexity. We will therefore hide this field from the content managers by not giving them the associated permissions.

This is easier than removing the functionality altogether. Furthermore, it makes it easier to add said functionality in the future, should we want it.

**Comment by bartromgens** [comment]
Ok, clear. Thanks.
