### ISSUE TITLE
Offer agenda of upcoming events per department

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#9]

**Comment by m-lies** [comment]
Currently, when creating an event in a department backend site, the option 'Event category' is mandatory. If you do not fill this in, the events will not be visible in the frontend (message 'Hmm.. something went wrong with loading the events.' is shown). 'Event category' should also be optional in department sites.

**Comment by m-lies** [comment]
The option to make all or several department events visible in the same agenda should be incorpated.

**Comment by Pieter1024** [comment]
The comment of @m-lies refers to the availability of the agendas of other departments on the main site. Refer to http://jongedemocraten.nl/component/jevents/month.calendar/ for an example.

**Comment by m-lies** [comment]
My previous comment on the visibility of all agendas on the main site can be ignored. This function is allready incorpated in the code :)

**Comment by sh4wn** [comment]
So I guess this issue can be closed?

**Comment by bashazeborg** [comment]
@m-lies , can this issue be closed? I think so.

**Comment by m-lies** [comment]
That depends, in the department backend site the option 'Event category' is still mandatory. @bashazeborg, do you want the option to be mandatory for the department sites? If so this issue can be closed.

**Comment by sh4wn** [comment]
Did you pull the latest version? The field shouldn't be mandatory anymore.

**Comment by sh4wn** [comment]
Wait, you'll have to upgrade the mezzanine-fullcalendar package with pip, or completely recreate the env.

**Comment by bashazeborg** [comment]
How do I do that?:)

Met vrijzinnige groet,

Bas Hazeborg

--

Landelijk Bestuur der Jonge Democraten
Algemeen Secretaris

Telefoon: 06 38977320
E-mailadres: secretaris@jongedemocraten.nl

2015-03-24 15:15 GMT+01:00 Lucas <notifications@github.com>:

**Comment by sh4wn** [comment]
1. Activate the virtual environment (source ./env/bin/activate)
2. pip uninstall swingtime
3. pip install --upgrade -e git+https://github.com/jonge-democraten/mezzanine-fullcalendar#egg=fullcalendar

**Comment by m-lies** [comment]
The additions look really good! Unfortunatly I still have a problem.. When I create a department event and do not fill in the field 'event category', then that particular department event is not visible on the frontend of the department site. I get an error message 'Hmm.. something went wrong with loading the events' and the agenda is shown completely empty (all other events are also no longer visible). 

Yet on the frontend of the main site that particular department event is shown in the agenda and everthing works perfectly.

**Comment by sh4wn** [comment]
That sounds like a bug indeed. I will look into that!

**Comment by Pieter1024** [comment]
I have another request. When I am on the national website (jd.local), the events of departments are visible. However, when I click one, I am not redirected to the department website: the event is just displayed in the context of the national website.

This behaviour is acceptable but confusing, because in the details page I can't see to which department an event belongs. Therefore please, either:

* add a 'department' field on the event details page, which states to which department an event belongs, or
* make sure the links in the agenda on the national website redirect to the department website to display the event details.

**Comment by bashazeborg** [comment]
I think the last option is most desirable and most easy to work with.

Met vrijzinnige groet,

Bas Hazeborg

--

Landelijk Bestuur der Jonge Democraten
Algemeen Secretaris

Telefoon: 06 38977320
E-mailadres: secretaris@jongedemocraten.nl

2015-03-28 21:53 GMT+01:00 Pieter1024 <notifications@github.com>:

**Comment by sh4wn** [comment]
Both things should be fixed now.

**Comment by Pieter1024** [comment]
So then this issue may be closed, @sh4wn ?

**Comment by m-lies** [comment]
I believe there is another bug. If you create an event with the status "Draft", the event is still visible in the agenda overview (despite not being logged in as admin). Hope this can be fixed.

**Comment by sh4wn** [comment]
This should be fixed now.
