### ISSUE TITLE
Make sure events and occurrences respect draft status

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#90]
Although Occurrences are now Displayable, they still do not neatly follow a set draft status.

When I set an event to draft:
* the event is still accessible through its direct URL (even when not logged in as admin);
* the event is not visible in /events/ and the event column and sidebar items when authenticated as admin.

In contrast, when I set a page to draft:
* the page is not accessible through its direct URL, yielding a 404 error (unless I am logged in as admin);
* the page is accessible and visible in the menu when I am authenticated as admin.

I suspect this is due to the selections we make in /fullcalendar/templatetags/fullcalendar.py, especially in functions such as get_site_agenda.

**Comment by bartromgens** [comment]
Thanks for testing. I will look into this.

**Comment by bartromgens** [comment]
This is fixed in fullcalendar commit https://github.com/jonge-democraten/website/commit/1db1e5ddf6c98a30fe563a346b1bec93e8ab9651.

**Comment by bartromgens** [comment]
Another issue where the main site was not found when no event category was set is fixed in commit https://github.com/jonge-democraten/mezzanine-fullcalendar/commit/1b547cb08a90e18d49c78ce722b0bd622f55b55a.

**Comment by bartromgens** [comment]
@Pieter1024, please verify that it works as expected now.

**Comment by Pieter1024** [comment]
@bartromgens , good work!

This almost works now. The URL to the draft event now indeed shows a 404 when I'm not logged in. The /events/ overview displays draft events when I'm not logged in. The same holds for the iCal overview (good thinking!). So far, so good.

However, the draft events are not displayed in the sidebar events element. They are also not displayed in the upcoming events column element on the homepage. I couldn't figure out quickly how to fix that, so I'll just leave this observation here :).

**Comment by bartromgens** [comment]
Good find!

Fixed in fullcalendar commit https://github.com/jonge-democraten/mezzanine-fullcalendar/commit/baa60658352f5c45f6f00f00484b1ae45a0572e7. 
Should work everywhere now.

Requires an env update to fullcalendar 0.6.3.

**Comment by Pieter1024** [comment]
Excellent work!

**Comment by bartromgens** [comment]
Created some basic tests for the integration with fullcalendar/events in commit https://github.com/jonge-democraten/website/commit/5dfdb627d34ce83d15a133b43b6890624d1fb995

Tests the visibility of published/draft status for normal users and admins.

Also tests the setting to show 'all', 'this site', and 'main + this site' events.

**Comment by Pieter1024** [comment]
\o/
