### ISSUE TITLE
Performance and load test on production server

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#91]
I installed https://github.com/locustio/locust locally to do some performance and load testing. 

An example run on a local jdwebsite django dev server in debug mode, with demo_data fixtures loaded, with 7 requests/s,

![jdsearch1](https://cloud.githubusercontent.com/assets/2451596/8366480/8ea6f52e-1b95-11e5-9749-7efb7772c1f8.png)

I will run this once there is a production server to get some insight in performance. It will show how the site performs in optimal and high load conditions by simulating users visiting a given list of urls.

**Comment by bartromgens** [comment]
This is the locust config file that I used. Can be used as example.

```python
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):
    def on_start(self):
        """ on_start is called when a Locust start before any task is scheduled """
        #self.login()

    @task(3)
    def index(self):
        self.client.get("/")

    @task(1)
    def blog(self):
        self.client.get("/example-blog/")

    @task(1)
    def calendar(self):
        self.client.get("/events/")

    @task(1)
    def documenten(self):
        self.client.get("/documenten/")


class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait=1000
    max_wait=5000
```

**Comment by Pieter1024** [comment]
Very nice. I think the performance in debug mode takes a particular hit from the debug toolbar.

**Comment by bartromgens** [comment]
Correct. I disabled the debug toolbar for these tests.

**Comment by bartromgens** [comment]
We could also run Google PageSpeed Insights, https://developers.google.com/speed/pagespeed/insights/, to get some basic tips on where we can or should improve.

**Comment by bartromgens** [comment]
The first results of some load tests, using locust, comparing the old (www.jd.nl) and new (website.jd.nl) website.

**New website, 1.5 request/s**:

| Name            | # requests | # failures | Median response time | Average response time | Min response time | Max response time | Average Content Size | Requests/s |
|-----------------|------------|------------|----------------------|-----------------------|-------------------|-------------------|----------------------|------------|
| /               | 82         | 0          | 360                  | 361                   | 205               | 553               | 27093                | 0.53       |
| /afdelingen/    | 17         | 0          | 330                  | 338                   | 287               | 417               | 26299                | 0.11       |
| /contact/       | 22         | 0          | 360                  | 376                   | 324               | 485               | 26795                | 0.14       |
| /events/        | 15         | 0          | 320                  | 356                   | 278               | 592               | 27059                | 0.1        |
| /organisatie/   | 16         | 0          | 340                  | 340                   | 259               | 563               | 26021                | 0.1        |
| /persberichten/ | 15         | 0          | 430                  | 431                   | 297               | 582               | 41414                | 0.1        |
| /politiek/      | 18         | 0          | 310                  | 331                   | 238               | 488               | 25611                | 0.12       |
| /word-lid/      | 20         | 0          | 1200                 | 1219                  | 919               | 1386              | 35234                | 0.13       |
| Total           | 205        | 0          | 360                  | 445                   | 205               | 1386              | 28621                | 1.33       |

**Old website, 1.5 requests/s**:

| Name            | # requests | # failures | Median response time | Average response time | Min response time | Max response time | Average Content Size | Requests/s |
|-----------------|------------|------------|----------------------|-----------------------|-------------------|-------------------|----------------------|------------|
| /               | 102        | 0          | 730                  | 799                   | 658               | 3610              | 37415                | 0.54       |
| /afdelingen/    | 21         | 0          | 700                  | 718                   | 659               | 954               | 35037                | 0.11       |
| /contact/       | 20         | 0          | 750                  | 885                   | 696               | 2918              | 33275                | 0.1        |
| /events/        | 24         | 0          | 320                  | 330                   | 282               | 432               | 27264                | 0.13       |
| /organisatie/   | 22         | 0          | 670                  | 803                   | 643               | 2907              | 34584                | 0.12       |
| /persberichten/ | 16         | 0          | 330                  | 337                   | 257               | 490               | 27264                | 0.08       |
| /politiek/      | 24         | 0          | 690                  | 719                   | 645               | 867               | 34896                | 0.13       |
| /word-lid/      | 17         | 0          | 2200                 | 2130                  | 1584              | 2472              | 27264                | 0.09       |
| Total           | 246        | 0          | 720                  | 808                   | 257               | 3610              | 34024                | 1.29       |

**Comment by bartromgens** [comment]
Google PageSpeed Insights gives a similar response time. 270 ms for new, 750 ms for old.

Google recommends,
> You should reduce your server response time under 200ms.

This requires profiling to find the performance bottleneck(s).

**Comment by trolando** [comment]
Still interesting that the site is much faster now. I did not know what to
expect regarding efficiency but this is certainly a nice result.

Perhaps using nginx vs apache2 might be fruitful. Other than that, an
analysis of the MySQL queries. Also Django recently added a values() and
values_list() methods to the queryset class that avoid building full blown
objects, using these more often might be a good idea. I've been doing this
for Hemres too.
Op 4 nov. 2015 07:57 schreef "Bart Römgens" <notifications@github.com>:

**Comment by Pieter1024** [comment]
I agree, these are very nice results.

I would propose to focus more on optimizing SQL queries than on changing the web server software. The reason is the discrepancy between different pages in their efficiency. If the 'word lid' page is so slow, we should index the appropriate database columns.

**Comment by trolando** [comment]
In addition some select_related and prefetch_related usage might be good
for performance.
Op 4 nov. 2015 14:22 schreef "Pieter1024" <notifications@github.com>:

**Comment by bartromgens** [comment]
I am also happy with the results. It is twice as fast and more consistent. Also more than acceptable for users. 

We have to profile before we optimize. Never done that before with Django though. 
I don't see it as high priority and would only spend time on it if someone likes it. I am also not a fan of more complex code for a small performance gain.

I tried the Profiler panel of the debug_toolbar, but did not get any output and there is little documentation.

**Comment by trolando** [comment]
Ah, I am a fan of profiling. While I agree that introducing complex code
for better performance is not important for us (we're not Facebook), I
would consider optimization of the database queries by using prefetching,
usage of values() and values_list() when we don't need full ORM objects,
and some indexing and caching, as simple and low-hanging fruit.

https://docs.djangoproject.com/en/1.8/topics/db/optimization/ should be
reading material. Again, these are understandable optimizations and don't
involve arcane code and magical programming.

A cursory search on the internet reveals that the Django Debug Toolbar
might introduce a ton of overhead, reducing its usefulness as a profiling
tool. I would consider trying https://github.com/mtford90/silk. Also, there
is a useful code snippet on
https://gun.io/blog/fast-as-fuck-django-part-1-using-a-profiler/ that we
might want to use.

**Comment by bartromgens** [comment]
Closing this issue because a performance test is done and no critical performance issues have been found. There are always ways to improve performance, but this is not required to go live.

**Comment by trolando** [comment]
I've fixed several performance issues in f0cf86153f3854de8270b06f99b2c6a901c30ba6.

**Comment by trolando** [comment]
In 6f9a681f07e763b644edf9f6aece6da0a737d9fd I added another small streamlining. Since the BlogPostItem wrapper will query the user information for each post anyway, it should be fetched in the first query,... using select_related.

**Comment by bartromgens** [comment]
Those changes look good @trolando. 

Here are the new locust results,

| Method | Name            | # requests | # failures | Median response time | Average response time | Min response time | Max response time | Average Content Size | Requests/s |
|--------|-----------------|------------|------------|----------------------|-----------------------|-------------------|-------------------|----------------------|------------|
| GET    | /               | 106        | 0          | 330                  | 323                   | 237               | 559               | 27348                | 0.58       |
| GET    | /afdelingen/    | 18         | 0          | 290                  | 296                   | 245               | 364               | 26430                | 0.1        |
| GET    | /contact/       | 19         | 0          | 330                  | 358                   | 288               | 613               | 28187                | 0.1        |
| GET    | /events/        | 17         | 0          | 290                  | 317                   | 215               | 614               | 26520                | 0.09       |
| GET    | /organisatie/   | 21         | 0          | 280                  | 280                   | 221               | 370               | 26079                | 0.11       |
| GET    | /persberichten/ | 20         | 0          | 440                  | 449                   | 384               | 535               | 41524                | 0.11       |
| GET    | /politiek/      | 22         | 0          | 270                  | 285                   | 205               | 451               | 25683                | 0.12       |
| GET    | /word-lid/      | 26         | 0          | 340                  | 357                   | 303               | 493               | 35349                | 0.14       |
| None   | Total           | 249        | 0          | 330                  | 330                   | 205               | 614               | 29009                | 1.36       |

This indicates an overall performance improvement of about 10%. /word-lid/ is 3x faster now! Great!

**Comment by bartromgens** [comment]
Close because performance is good at the moment.
