### ISSUE TITLE
Change password functie overbodig

### ISSUE THREAD

**Issue by miekedewit** [jonge-democraten/website#93]
Rechtsbovenaan de pagina staat de optie change password, deze is overbodig omdat er gebruik wordt gemaakt van mijnjd-accounts.

**Comment by floort** [comment]
Dit gaat om de admin interface. Work-around kan zijn: verbergen met css.

**Comment by Pieter1024** [comment]
Mogelijk kunnen we een custom template maken voor admin, dat afgeleid is van de gewone template. De gewone template bevat een block voor custom CSS.

**Comment by Pieter1024** [comment]
De gewone template staat trouwens in grappelli_safe/templates/admin/base.html.

**Comment by Pieter1024** [comment]
Ik heb inderdaad een admin-template override gemaakt, zie commit a52c06936b7615faa57146431f76d37d56c41a4f. De 'Change password'-knop wordt nu zowel verborgen met CSS als met JavaScript. Met CSS, omdat dat netter en sneller is. Met JavaScript, omdat we dan ook het <li>-element er omheen kunnen verbergen.

@miekedewit kun jij dit issue sluiten als je hebt gecontroleerd dat 'Change password' inderdaad niet meer zichtbaar is in de admin-omgeving?
