### ISSUE TITLE
Pages not displayed in menus

### ISSUE THREAD

**Issue by malupasman** [jonge-democraten/website#94]
At the moment, the homepages do not provide us with the correct pages. E.g. When one goes to 'website.jd.nl', It shows the message that the page cannot be found. Furthermore, this page currently uses the JD Amsterdam template instead of the national template.

On some of the department pages, another issue is apparent. When one goes to 'groningen.jd.nl', the visitor will see the national homepage.

**Comment by Pieter1024** [comment]
This issue mentions three problems:
1. The correct pages are not displayed.
2. The incorrect template is used.
3. The domain names are sometimes redirected to the old website.

I think I fixed issues 2 and 3. Could you check this?

**Comment by Pieter1024** [comment]
I assume we are only still talking about point 1: the old pages are not properly displayed in menus yet.

**Comment by floort** [comment]
Lijkt opgelost door @Pieter1024. Nieuw issue is dat de titels van de pagina's te lang zijn voor de menu's.
@miekedewit kan je kijken of deze gesloten kan worden?

**Comment by Pieter1024** [comment]
Een corectie t.o.v. wat @floort zei:

In Joomla heeft een pagina een titel (bovenaan de pagina als hij open staat) en een menuvermelding (de tekst in het menu waar je op klikt om de pagina te openen). Die hoeven niet gelijk te zijn.

In Mezzanine is er geen onderscheid tussen die twee. De simpele oplossing is om een van de twee te gebruiken en de andere weg te doen. De menuvermelding is dan de logische keuze omdat de titel vaak te lang is om goed in het menu te passen. In de huidige uitwerking doen we dat inderdaad zo.
