### ISSUE TITLE
Subscriptions voor newsletter migreren

### ISSUE THREAD

**Issue by floort** [jonge-democraten/website#96]

**Comment by Pieter1024** [comment]
De subscriptions vallen in twee typen uiteen, die ook fundamenteel verschillend moeten worden afgehandeld:

#### Leden (JaneusSubscriber)

JaneusSubscribers hebben vier velden:
* name (van Subscriber) (wordt onder meer gebruikt als aanhef in de nieuwsbrieven)
* janeus_name (onduidelijk wat de functie is, is standaard gelijk aan name)
* member_id (lidnummer uit de database, unique identifier om mailadres mee op te halen)
* subscriptions (ManyToManyField voor nieuwsbriefinschrijvingen, van Subscriber)

#### Andere inschrijvers (EmailSubscriber)

EmailSubscribers hebben in plaats van de velden janeus_name en member_id het veld email. Dit is de unieke index waarop deze inschrijvers van elkaar worden onderscheiden.

#### Voorgestelde aanpak bij migratie

Ik stel het volgende voor:
1. Maak eerst de nieuwsbrieven aan en daarna pas de subscribers. Dan kun je de subscriptions meteen goed instellen.
2. Na het aanmaken van de nieuwsbrieven: zet de EmailSubscribers over. Alle gegevens voor het aanmaken staan ook al zo in de oude database. Het zou een recht-op-en-neer-conversie moeten zijn.
3. Zet vervolgens de leden over. Deze staan ook al apart in onze oude subscriptions-tables. Bij leden moet je bij het e-mailadres het juiste lidnummer opvragen vanuit de LDAP-directory. Daarvoor is het nuttig eerst na te gaan dat alle emailadressen inderdaad uniek zijn. Vervolgens script je tegen LDAP aan om te vragen welk lidnummer er bij een bepaald e-mailadres hoort. De code daarvoor zou je direct moeten kunnen lenen van Toms login voor het congresvoorstelsysteem. Dan haak je direct in op bestaande functionaliteit van Janeus. De juiste call staat op https://github.com/jonge-democraten/zues/blob/master/zues/views.py#L79.

Laat het vooral weten als je nog meer hulp nodig hebt.

**Comment by Pieter1024** [comment]
En @trolando laat het graag weten als je hier andere ideeën over hebt.

**Comment by Pieter1024** [comment]
Als jij trouwens zorgt dat je lege nieuwsbrieven en templates gebruikt, zal ik ze vullen vanuit het jd_finalize script. Wel graag verschillende templates voor verschillende nieuwsbrieven gebruiken (de templates voor verschillende afdelingen zijn verschillend).

**Comment by trolando** [comment]
Klinkt als een goed voorstel. Je wil eerst elke MailingList maken. Daarna kun je pas subscribers toevoegen.

**Comment by Pieter1024** [comment]
Dit werkt nu. Zie de laatste commits van Floor.

@miekedewit kun je bekijken dat alle functionaliteit er is? De werking van het verzenden van nieuwsbrieven moet je nog even tegoed houden, daar zorgt Tom dit weekend voor. Daarna kunnen we de verzending gaan testen.

**Comment by Pieter1024** [comment]
Mieke ontvangt de bijbehorende mails niet, zowel als lid van een mailinglijst als als testmails. We hebben getest met haar secretaris-adres, waar een Gmail-inbox achter hangt. Hij wordt wel verstuurd door de server maar komt niet omhoog in haar inbox.

**Comment by Pieter1024** [comment]
Ik kon dit symptoom niet reproduceren met mijn eigen Gmail-adres of met mijn eigen jd.nl-adres. Het lijkt erop dat alleen het secretaris-adres dit probleem heeft. Dat zou kunnen komen doordat het ook al @jongedemocraten.nl geregistreerd staat.

@miekedewit kun je proberen je te registreren voor een nieuwsbrief met een Gmailadres en laten weten of het dan wel lukt?

**Comment by Pieter1024** [comment]
We gebruiken dit systeem inmiddels al lang en breed in productie. Ik sluit daarom dit issue.
