### ISSUE TITLE
Migratiescript vraagt om domeinnaam maar voegt www.jongedemocraten.nl toch apart toe

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#98]
Het migratiescript vraagt aan het begin om een eerste domeinnaam. Dat moet website.jongedemocraten.nl zijn (wordt later jongedemocraten.nl). Echter, in die domeinnaam slaat hij niks op. In plaats daarvan maakt hij de aparte Site www.jongedemocraten.nl aan. Hij moet deze data juist opslaan in die eerste gemaakte site (ongeacht de domeinnaam die deze heeft gekregen).

**Comment by floort** [comment]
@Pieter1024 Klopt het dat deze ticket niet meer relevant is wanneer het migrate.sh wrapper script gebruikt word?

**Comment by floort** [comment]
Gisteren gefixt. Ik sluit 'm zonder revieuw.
